version: 2
jobs:
  build:
    working_directory: /tmp/rube
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
            name: Test
            command: echo "Deploying rube"
      - run:
           name: Install awscli
           command: sudo pip install awscli
      - deploy:
           name: Create appication
           #command: aws s3 sync . s3://rubegoldberg082479.s3.amazonaws.com --delete
           command: aws deploy create-application --application-name HelloWorld_App
      - deploy:
           name: Push application   
           command: aws deploy push --application-name HelloWorld_App --s3-location s3://rubegoldberg082479.s3.amazonaws.com --ignore-hidden-files
