version: 2
jobs:
  build:
    working_directory: /tmp/rube
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
            name: Test
            command: echo "Deploying rube"
      - run:
           name: Install awscli
           command: sudo pip install awscli
      - deploy:
          name: Deploy to S3 if branch is Master.
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              command: aws s3 sync . s3://rubegoldberg082479.s3.amazonaws.com --delete
            fi
